export const COUNT_AMOUNT_OF_INGREDIENTS_ADD:'COUNT_AMOUNT_OF_INGREDIENTS_ADD' = 'COUNT_AMOUNT_OF_INGREDIENTS_ADD';
export const COUNT_AMOUNT_OF_INGREDIENTS_DELETE:'COUNT_AMOUNT_OF_INGREDIENTS_DELETE' = 'COUNT_AMOUNT_OF_INGREDIENTS_DELETE';
export const CHANGE_INGREDIENT_ORDER:'CHANGE_INGREDIENT_ORDER' = 'CHANGE_INGREDIENT_ORDER';
export const INITIAL_STATE:'INITIAL_STATE' = 'INITIAL_STATE';
export const SET_BUN:'SET_BUN' = 'SET_BUN'
