export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_ON_MESSAGE_RECEIVED: 'WS_ON_MESSAGE_RECEIVED' = 'WS_ON_MESSAGE_RECEIVED';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE'
export const WS_ON_MESSAGE_RECEIVED_PROFILE: 'WS_ON_MESSAGE_RECEIVED_PROFILE' = 'WS_ON_MESSAGE_RECEIVED_PROFILE'